---
# Jekyll options.
name: EVE Online Overview Generator
domain: http://io.evansosenko.com/eve-overview
baseurl: http://io.evansosenko.com/eve-overview
markdown: redcarpet
highlighter: pygments

# Uncomment below to enable pagination.
# paginate: 5

exclude:
  - CHANGELOG.md
  - LICENSE.txt
  - README.md
  - VERSION
  - Gemfile.lock
  - Gemfile
  - Rakefile
  - bower.json
  - bower_components

gems:
  - json
  - jekyll-assets
  - jekyll-assets/compass
  - coffee_script

# Jekyll::AssetsPlugin options.
assets:
  baseurl: http://io.evansosenko.com/eve-overview/assets/
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - bower_components
  compress:
    css: sass
    js: uglifier

# Use a cdn to load some libraries.
cdn_enabled: true
cdn:
  # [ url, fallback test, local asset fallback path ]
  libs:
    - [ "https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js", "!window.jQuery", "jquery/dist/jquery" ]

# Keywords will be merged with categories, tags, and page keywords.
keywords: [ eve online, eve, overview, overviews, overview generator, tool, yaml, yml, ruby, dry ]

# Uncomment below to set default meta info.
meta:
  locale: en_US
  description: "Generate DRY modular overviews for EVE Online."
  title:
    prefix: ""
    suffix: ""
  twitter:
    default_card: summary
    site: "@evansosenko"
    creator: "@evansosenko"

# Uncomment below and add your Disqus Shortname to enable Disqus.
# disqus: shortname

# Uncomment below and add your Tracking ID and URL to enable Google Analytics.
google_analytics:
  id: UA-19631381-4
  url: evansosenko.com

# Uncomment below and add your Piwik URL to enable Piwik.
# piwik: https://example.com/piwik/

# Uncomment below to enable deploy.
# :deploy:
#   # only :rsync supported
#   :protocol: :rsync
#   # domain name
#   :server: example.com
#   # remote username
#   :user: www
#   # remote port
#   :port: 22
#   # path to remote folder where contents of _site should go
#   # must have trailing slash
#   :path: /var/www/example.com/htdocs/
#   # site files and folders that should be uploaded but not synced
#   # remote content will not be removed from these files and folders
#   :upload_only:
#     - content/

# Foundation Interchange markup support added to
# Jekyll Picture Tag (https://github.com/robwierzbowski/jekyll-picture-tag)
# Uncomment below to enable responsive images.
# picture:
#   markup: 'interchange'
#   source: pictures/fullsize
#   output: pictures
#   presets:
#     default:
#       ppi: [ 1, 1.5, 2 ]
#       source_large:
#         media: '(large)'
#         width: '1440'
#       source_medium:
#         media: '(medium)'
#         width: '1280'
#       source_small:
#         media: '(small)'
#         width: '768'
#       source_default:
#         width: '500'

# Uncomment below to configure social media.
social:
  facebook:
    enabled: true
  google:
    enabled: true
    gcfg:
      lang: en-US
      parsetags: onload
  twitter:
    enabled: true

# Include code from other repos in the final build.
# Each array has the format
# - [ repo, branch, subdirectory, treeish (optional) ]
# Uncomment this example to includes a copy of the gh-pages branch of this repo at
# http://io.evansosenko.com/eve-overview/inception/jekyll-and-zurb/
# :sub_content:
#   - [ "https://github.com/razor-x/jekyll-and-zurb", gh-pages, inception/jekyll-and-zurb ]

# GitHub source repository.
source_repo: razor-x/eve-overview
